### ISSUE TITLE
Make a release please

### ISSUE THREAD

**Issue by ondrejj** [amol-/linetable#1]
Because this package is needed for kajiki, I need to build a Fedora package. Please make a release to make this easier. Thank you.

**Comment by kloczek** [comment]
https://pypi.org/project/linetable/ already says thjat latest version in 0.0.2 so it would be good to add at least git tag for that version.

**Comment by kloczek** [comment]
It would be good to add tag as sdist tar ball is stipped test suite.

**Comment by amol-** [comment]
I recorded the two releases in github. Is that what you needed?

**Comment by ondrejj** [comment]
Yes. Thank you very much. Starting a Fedora package review process.
